
import Head from 'next/head'




import Image from 'next/image'
import om from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web3 from '../public/image1.png'
import web1 from '../public/image2.png'
import web2 from '../public/image3.png'
import web4 from '../public/image4.png'
import web5 from '../public/image5.png'
import web6 from '../public/image6.png'
import React, { useState } from 'react'


import { BsFillMoonStarsFill, BsFillTelephoneFill } from 'react-icons/bs'
import { AiFillLinkedin, AiFillBehanceSquare } from 'react-icons/ai'
import { HiMail, HiLocationMarker } from 'react-icons/hi'
import { FaGithubSquare } from 'react-icons/fa'




export default function Home() {
  const [darkMode, setdarkMode] = useState(false)
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head children={undefined}>
        <title>om portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40'>
        <section className=" min-h-screen">
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>developedbyom</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setdarkMode(!darkMode)} className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://drive.google.com/uc?export=download&id=1oTC82uUk-H0TJ6oGOhlHMitMMiZ97_ar">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className='text-5xl py-2 text-teal-600 font-medium  dark:text-teal-400 md:text-6xl'>Om Kumar</h2>
            <h3 className='text-2xl py-2 dark:text-white md:text-3xl'>Web Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-2xl mx-auto md:text-xl'>After researching the latest web design trends , and according to your site’s purpose and strategy , I create unique and quality Design to make sure your website look professional and attractive , And you get it all at an unbeatable price.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='https://www.linkedin.com/in/om-kumar-707762201/' target={'_blank'}><FaGithubSquare /></a>
            <a href='https://www.behance.net/omkumar20cs105' target={'_blank'}><AiFillBehanceSquare /></a>
            <a href='https://www.linkedin.com/in/om-kumar-707762201/' target={'_blank'}><AiFillLinkedin /></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={om} layout='fill' objectFit='cover' />
          </div>
        </section>
        {/* another section */}

        <section>
          <div>
            <h3 className='text-3xl py-1 mt-16 dark:text-white text-center'>Service I offer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200 text-center'>
              After researching the latest web design trends , and according to your site’s purpose and strategy , I create unique and quality Design to make sure your website look professional and attractive , And you get it all at an unbeatable price.
            </p>
            <p className='text-md py-5 leading-8 text-center text-gray-800 dark:text-gray-200'>
              I have a strong understanding of industry trends and content management systems (WordPress) along with Responsive and adaptive design experience. I also understand the entire web development process including design, development and deployment.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                After researching the latest web design trends , and according to your site’s purpose and strategy , I create unique and quality Design to make sure your website look professional and attractive
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Adobe XD</p>
              <p className='text-gray-800 py-1'>Adobe Illustrator</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Development</h3>
              <p className='py-2'>
                Developing fully customized , responsive / mobile friendly and SEO ready Static and Dynamic websites at very affordable price , i built your website around a target audience and market.
              </p>
              <h4 className='py-4 text-teal-600'>Development Libraries I use</h4>
              <p className='text-gray-800 py-1'>React JS</p>
              <p className='text-gray-800 py-1'>Vue JS</p>

            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 '>
              <Image src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Logo Designs</h3>
              <p className='py-2'>
                Logo should reflect the company in a unique and honest way . Making simple , attractive and relevant logo solution for your business websites.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Adobe XD</p>
              <p className='text-gray-800 py-1'>Adobe Illustrator</p>
            </div>

          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 mt-16 dark:text-white text-center'>Portofolio</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200 text-center'>
              I create successful responsive websites that are fast, easy to use, and built with best practices. The main area of my expertise is front-end development, <span className='text-teal-500'> HTML, CSS, JS, React JS, Vue JS</span> building small and medium web apps, features, animations, and  interactive layouts.

            </p>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200 text-center'>
              Feel free to look down here!
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
          </div>
        </section>
        <div className='flex w-full min-h-screen justify-center items-center'>
              <div className='flex flex-col md:flex-row md:space-x-48 md:space-y-0 bg-cyan-700 w-full max-w-6xl p-8 sm:p-12 rounded-xl shadow-lg text-white overflow-hidden'>
                <div className='flex flex-col space-y-4 justify-between md:w-8xl'>
                  <div>
                    <h1 className='font-bold text-4xl tracking-wide'>Take a coffee and chat with me 🍵</h1>
                    {/* <p className='pt-2  text-cyan-100 text-sm'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis quos repellat velit deserunt eligendi deleniti adipisci dignissimos esse. Harum, vel.</p> */}
                  </div>
                  <div className='flex flex-col space-y-6'>
                    <div className='inline-flex space-x-2 items-center'>
                      <BsFillTelephoneFill name='call' className='text-teal-300 text-xl' />
                      <span>+ ( 91 ) 9950381074</span>
                    </div>
                    <div className='inline-flex space-x-2 items-center'>
                      <HiMail name='mail' className='text-teal-300 text-2xl' />
                      <span>jssom.1115@gmal.com</span>
                    </div>
                    <div className='inline-flex space-x-2 items-center'>
                      <HiLocationMarker name=' location' className='text-teal-300 text-2xl'/>
                      <span>F1, Sector 58, Noida</span>
                    </div>
                  </div>
                  <div className='flex space-x-4 text-3xl'>
                    <a href='https://www.linkedin.com/in/om-kumar-707762201/' target={'_blank'}><FaGithubSquare /></a>
                    <a href='https://www.behance.net/omkumar20cs105' target={'_blank'}><AiFillBehanceSquare /></a>
                    <a href='https://www.linkedin.com/in/om-kumar-707762201/' target={'_blank'}><AiFillLinkedin /></a>
                  </div>
                </div>
                <div className='relative mt-12'>
                  <div className='absolute w-40 h-40 bg-teal-400 rounded-full -right-28 -top-28'></div>
                  <div className='absolute w-40 h-40 bg-teal-400 rounded-full -left-28 -bottom-24'></div>
                  <div className='relative z-10 bg-white rounded-xl shadow-lg p-8 text-gray-600 md:w-max'>
                    <form action="" className='flex flex-col space-y-4 '>
                      <div>
                        <label htmlFor="" className='text-sm '>Your Name</label>

                        <input type="text" placeholder='Your Name' className='ring-1 ring-gray-300 w-full rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-teal-300' />
                      </div>
                      <div>
                        <label className='text-sm '>Email Address</label>

                        <input type="email" placeholder='Email Address' className='ring-1 ring-gray-300 w-full rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-teal-300' />
                      </div>
                      <div>
                        <label htmlFor="" className='text-sm '>Message</label>

                        <textarea placeholder='Message' rows='4' className='ring-1 ring-gray-300 w-full rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-teal-300' />
                      </div>
                      <button className='inline-block self-end bg-cyan-700 text-white font-bold rounded-lg px-6 py-2 text-sm uppercase'>Send Message</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <footer className=' text-center dark:text-gray-200 dark:bg-gray-900'>
              <p>Made with ❤️ By OM</p>
      </footer>
      </main>
     
    </div>
  )
}
